name: Nuget Packages

on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 5.0.x

      - name: Setup pipenv
        run: python -m pip install --upgrade pipenv

      - name: Setup MkDocs
        run: |
          cd $GITHUB_WORKSPACE
          python -m pipenv install --dev

      - name: Setup Tools
        run: |
            dotnet tool restore
            dotnet paket restore

      - name: Build Package
        run: |
          cd $GITHUB_WORKSPACE
          dotnet fake run ./build.fsx target Packages

      - name: Upload
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PIP_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          pipenv run twine upload --repository pypi dist/*

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Tar Archive Artifact
          path: ./src/**/*.nupkg
